### ISSUE TITLE
War Banner

### ISSUE THREAD

**Issue by Rosu-Catalin** [ProSavage/SavageFactions#128]
**Describe the bug**
I cant use war banner

**To Reproduce**
2. Issue command '...'
3. Walk to '...'

**Expected behavior**

**Screenshots**
https://pastebin.com/f9iYzg7H

**Server VErsion (please complete the following information):**
 - Spigot Version: [e.g. Paperspigot 1.8.8]: Paper 1.8.8
 - Factions Version [use /f version] Factions v1.6.9.5-U0.2.1-RC-1.6-RC
 - Minecraft Version: [If a bug is dependent on client version]

**Additional context**

**Comment by SvenjaReissaus** [comment]
Would you please be kind and fulfill the format?

**Comment by SvenjaReissaus** [comment]
Please re open the issue when you can fulfill the format.

**Comment by SvenjaReissaus** [comment]
Reeeeee I'm sorry lmfao

**Comment by partydev** [comment]
Experiencing this issue too on the latest version.

**Comment by prosavage** [comment]
Hey, so noSuchMethod errors are caused by the jar file that is running your server, not having the method. Your version string is weirdly named, so I cannot tell like normal if its like 1.12 or 1.7 etc... Please tell me the correct version and maybe give me the jar file!
![image](https://user-images.githubusercontent.com/29169519/55362906-0f058a80-54a1-11e9-9052-5991364af431.png)

**Comment by partydev** [comment]
Was this fixed?
