### ISSUE TITLE
[Bug] Error when using /f perms interface

### ISSUE THREAD

**Issue by KarlOfDuty** [ProSavage/SavageFactions#196]
**Describe the bug**
Players are having issues updating their factions permissions using the /f perms interface, which is throwing an error in the console. It doesn't seem to happen to everyone every time, but it is very common causing players to complain.

**To Reproduce**
1. Use /f perms
2. Click on perms to edit
3. Nothing happens for user, error in console

**Expected behavior**
Permission is updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/18099825/62009975-4a6d4880-b165-11e9-9cbf-329874494125.png)

**Server Version (please complete the following information):**
 - Spigot Version: Paperspigot 639 (1.13.2)
 - Factions Version: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3.1

**Comment by KarlOfDuty** [comment]
More info here:

https://github.com/EarthMC/Issue-Tracker/issues/650

**Comment by xSkate** [comment]
I'm also having this issue and I've taken some time to figure out what caused/causes it.
Here's the rundown: I converted from FactionsUUID a while ago to the latest SavageFactions release from Spigot with no problems. Any factions that were created while I was using FUUID, if I use the latest revision of SF from GitHub, have that error you posted when trying to access sections of f perm. If someone creates a new faction, f perm can be accessed no problem.
Did some fiddling around with old versions and I found this issue is not present before commit 670b2bcf3c5dc49f706604e825282a1cc0ea3d2a. I'm able to use the revision at commit 382733eefc5fa96130243b2534817b298c073a08 with no problems. I don't really have the skills to fix this for myself, but I hope this information may be of some use.

**Comment by Savag3life** [comment]
This is a config error, not a plugin error. Please reset your config.yml file to resolve this issue.

**Comment by KarlOfDuty** [comment]
This issue was not fixed by using a new config. I have completely rebuilt both configs from the latest version but it is still broken.

**Comment by prosavage** [comment]
Hey Karl, if you update to a dev build from https://savagellc.net/downloads

You will have a fixed version.

**Comment by KarlOfDuty** [comment]
Yes, seems to have fixed this issue.
